spring.application.name=Projeto.Integrador
firebase.project-id=projetointegrador-4f2dd
firebase.database-url=https://projetointegrador-4f2dd-default-rtdb.firebaseio.com
firebase.credentials-path=.firebase/serviceAccountKey.json
